### ISSUE TITLE
MPFI interface does not implement Floor()

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/float#25]
Hence also Round() and other functions don't work.

If this is not an oversight, but intentional or due to a limitation of MPFI or whatever, perhaps there could still be a method installed which outputs an informative error, like "Floor() is not available for MPFI floats" ?

Also, perhaps `tst/arithmetic.tst` should cover more (all?) float "basis" functions, so that completeness of floating point implementations gets verified? For GAP, we use https://codecov.io to get an idea about which of course GAP and C code lines get execute and which not, helps a lot in writing additional tests to test code that is so far not exercised by tests.

**Comment by laurentbartholdi** [comment]
MPFI doesn't have Floor, but it could be added without too much trouble. As for Round and Ceil, idem. I don't know what Frac is supposed to return.

I don't know much about codecov, but the idea of running a bash script without having an idea of what it does, so that something gets uploaded to a mystery place, freaks me out. How do you use it?

**Comment by laurentbartholdi** [comment]
OK, well I just added the commands, making them work coordinatewise (except Frac which rounds down for the first, up for the second argument). This seems to be the only reasonable thing to do. I'm not sure it's so useful, though:
```
gap> x := Frac((1.0/3)*3);
∅
gap> Inf(x);
.1e1
gap> Sup(x);
.157772e-29
```
